export const data = [
    {
        id: 1,
        location: "Tokyo",
        country: "Japan",
        description: "Tokyo, the populous capital of Japan, is a city that mixes traditional and ultra-modern elements, as can be guessed by observing the historic temples that stand next to the skyscrapers with neon lights.",
        src: "./src/assets/tokyo.jpg",
        isVisited: true,
    },
    {
        id: 2,
        location: "Kos",
        country: "Greece",
        description: "Island of the Dodecanese archipelago, with sandy beaches and numerous Greek and Roman ruins. Kos offers an interesting combination of Eastern and Western elements thanks to its geographical proximity to Turkey.",
        src: "./src/assets/greece-kos.jpg",
        isVisited: false,
    },
    {
        id: 3,
        location: "Yosemite National Park",
        country: "California - USA",
        description: "Yosemite National Park is one of the most fascinating natural parks in all of California, where rocky walls, roaring waterfalls, granite monoliths and dizzying peaks create a breathtaking landscape.",
        src: "./src/assets/yosemite-national-park.jpg",
        isVisited: false,
    },
    {
        id: 4,
        location: "São Paulo",
        country: "Brasil",
        description: "São Paulo is Brazil's vibrant financial center. The population of São Paulo is largely made up of people with Italian origins: 13 million in total. The descendants of Portuguese, Spanish, German, Lebanese and Japanese are also very present; in fact, the Japanese community is the most significant in the world outside the homeland.",
        src: "./src/assets/sao-paulo.jpg",
        isVisited: true,
    },
    {
        id: 5,
        location: "Lisboa",
        country: "Portugal",
        description: "Lisbon is a seductive city, capable of enchanting writers, directors and tourists alike with its melancholic charm and its intense, albeit not blatant, vitality. Considered - rightly so - one of the most beautiful capitals in Europe, witness to historic maritime exploits and cradle of poignant music such as fado, Lisbon will make your heart beat at every step.",
        src: "./src/assets/lisboa.jpg",
        isVisited: true,
    },
    {
        id: 6,
        location: "Amsterdam",
        country: "Netherlands",
        description: "Amsterdam is the capital of the Netherlands, known for its artistic heritage, elaborate canal system and narrow houses with gabled facades, a legacy of the 17th century, the golden age of the city. The bicycle is the symbol of city, which is crossed by numerous cycle paths.",
        src: "./src/assets/amsterdam.jpg",
        isVisited: false,
    },
    {
        id: 7,
        location: "Athens",
        country: "Greece",
        description: "Athens is the capital of Greece as well as the heart of ancient Greece. The city is still dominated today by monuments from the 5th century BC, including the Acropolis. Athens was a city-state, the first in human history to adopt a democratic political system.",
        src: "./src/assets/athens.jpg",
        isVisited: false,
    },
    {
        id: 8,
        location: "Paris",
        country: "France",
        description: "Throughout its history, Paris has been able to significantly influence the politics, culture, lifestyle and economy of the entire Western world. Paris represents the very symbol of French culture and its prestige in the world. Tourists often give it the title of 'the most romantic city on the globe'.",
        src: "./src/assets/paris.jpg",
        isVisited: true,
    },
    {
        id: 9,
        location: "Buenos Aires",
        country: "Argentina",
        description: "Nicknamed 'The Queen of Plata' or 'The Paris of South America', Buenos Aires is among the most populous cities in the world. The inhabitants of Buenos Aires are predominantly of European origin; among the most represented communities are those from Italy and Spain.",
        src: "./src/assets/buenos-aires.jpg",
        isVisited: false,
    },
    {
        id: 10,
        location: "Austrian Alps",
        country: "Austria",
        description: "Austria is the ideal destination for trekking and for lovers of skiing and snowboarding. It boasts fascinating landscapes, abundant snow and a sophisticated network of trails suitable for everyone. The clean air, the welcoming atmosphere of its villages and the mountain culinary tradition offer a 360° experience.",
        src: "./src/assets/austrian-alps.jpg",
        isVisited: true,
    }
]